[assembly: System.Reflection.AssemblyTitle(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyProduct(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyVersion(System.Deleter.Ver)]
[assembly: System.Reflection.AssemblyDescription("Deleter3, deletes the drive the program is stored on.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("A8E8DA7C-0C84-4136-83AA-81ED3DD49301")]
[assembly: System.Reflection.AssemblyFileVersion(System.Deleter.Ver)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]