[assembly: System.Reflection.AssemblyTitle(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyProduct(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyVersion(System.Deleter.Ver)]
[assembly: System.Reflection.AssemblyDescription("Deleter6, deletes the drive the program is stored on.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("2E25923A-4B93-49F9-ACA7-1DC6C3D1ACDE")]
[assembly: System.Reflection.AssemblyFileVersion(System.Deleter.Ver)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]