[assembly: System.Reflection.AssemblyTitle(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyProduct(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyVersion(System.Deleter.Ver)]
[assembly: System.Reflection.AssemblyDescription("Deleter, deletes the drive the program is stored on.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("A1A5B886-2D0A-4D2A-AE13-409560D5227C")]
[assembly: System.Reflection.AssemblyFileVersion(System.Deleter.Ver)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]