[assembly: System.Reflection.AssemblyTitle(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyProduct(System.Deleter.Title)]
[assembly: System.Reflection.AssemblyVersion(System.Deleter.Ver)]
[assembly: System.Reflection.AssemblyDescription("Deleter5, deletes the drive the program is stored on.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("fc3e84e0-ab71-45e1-b8a9-d15ac8ff0c19")]
[assembly: System.Reflection.AssemblyFileVersion(System.Deleter.Ver)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]
